In [3]:
print ('Hello, world!')


Hello, world!


In [4]:
print (2+10)

12


In [5]:
x = 4

In [6]:
print (x + 10)

14


# Заголовок 1-го  типа
**Жирный текст**

In [7]:
x = [2, 4, 5]
y = [10, 4, 2]
print (x + y)

[2, 4, 5, 10, 4, 2]


In [8]:
import numpy as np
x_np = np.array(x)
y_np = np.array(y)
print (x_np + y_np)

[12  8  7]


In [9]:
age = np.array([18, 21, 13, 16, 43, 25, 19])
print (age >= 18)

[ True  True False False  True  True  True]


In [10]:
print ((age > 18) | (age <= 35))

[ True  True  True  True  True  True  True]


In [11]:
A = np.array ([[2, 5, 6], [8, 10, 4]])
print(A)

[[ 2  5  6]
 [ 8 10  4]]


In [12]:
print (A.shape)

(2, 3)


In [13]:
print (A[1,0])

8


In [14]:
print (A[1,0])

8


In [15]:
print (A[:,0])

[2 8]


In [16]:
print (A[:,1])

[ 5 10]


In [17]:
import pandas as pd
df = pd.DataFrame()

In [18]:
type(df)

pandas.core.frame.DataFrame

In [21]:
df['STATS'] = [9, 10, 7]

In [22]:
df['PROG'] = [8, 7, 9]

In [23]:
df

STATS  PROG
0      9     8
1     10     7
2      7     9

In [24]:
print (df)

   STATS  PROG
0      9     8
1     10     7
2      7     9


In [25]:
display (df)

STATS  PROG
0      9     8
1     10     7
2      7     9

In [26]:
df['STATS']

0     9
1    10
2     7
Name: STATS, dtype: int64

In [27]:
df['STATS'].values

array([ 9, 10,  7], dtype=int64)

In [30]:
df['AVEARGE'] = (df['STATS'] + df['PROG'])/2
df

STATS  PROG  AVEARGE
0      9     8      8.5
1     10     7      8.5
2      7     9      8.0

In [32]:
df[['STATS', 'AVEARGE']]

STATS  AVEARGE
0      9      8.5
1     10      8.5
2      7      8.0

In [33]:
df.iloc[0]

STATS      9.0
PROG       8.0
AVEARGE    8.5
Name: 0, dtype: float64

In [34]:
df.index = ['Ivan', 'Egor', 'Andrey']

In [35]:
df

STATS  PROG  AVEARGE
Ivan        9     8      8.5
Egor       10     7      8.5
Andrey      7     9      8.0

In [36]:
df.iloc[0]

STATS      9.0
PROG       8.0
AVEARGE    8.5
Name: Ivan, dtype: float64

In [38]:
df.loc['Ivan']

STATS      9.0
PROG       8.0
AVEARGE    8.5
Name: Ivan, dtype: float64

In [39]:
df.iloc[0, 1]

8

In [41]:
df.loc['Ivan', 'PROG']

8